### ISSUE TITLE
Sponsors and Exhibitors Page Is Broken

### ISSUE THREAD

**Issue by rschulman** [gembarrett/coconduct-builder#25]
I can't click on "Yes" or "No" and have it be selected, and therefore can't click "Next".

Mac OSX 10.10.5, Chrome 47.0.2526.80.

**Comment by gembarrett** [comment]
Related to #14 - blocker on #15

**Comment by wwork** [comment]
confirmed using Mac 10.10.5 with Firefox and Safari

fwiw: in Firefox 42.0, when I hit Skip the Rest on this page, I got a display box--couldn't select/copy the text of the CoC so far. Text selection worked in Safari.
